// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetResult() {
  return window['go']['main']['App']['GetResult']();
}

export function GetVersionInfo() {
  return window['go']['main']['App']['GetVersionInfo']();
}

export function StoreResult(arg1) {
  return window['go']['main']['App']['StoreResult'](arg1);
}
