// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetResult():Promise<string>;

export function GetVersionInfo():Promise<main.Version>;

export function StoreResult(arg1:{[key: string]: any}):Promise<void>;
