name: 'Build application'
on:
  workflow_dispatch:
    inputs:
      manual:
        description: 'Default value for tiggered workflows'
        type: boolean
        required: false
        default: true
  pull_request:
    branches:
      - develop
  push:
    branches:
      - develop
      - main
jobs:
  target-setup:
    name: 'Set up ENV'
    runs-on: 'windows-latest'
    outputs:
      env: ${{ steps.setvars.outputs.env }}
    steps:
      - name: Set build environment
        id: setvars
        shell: bash
        run: |
          if [[ ${{ github.ref_name }} =~ develop || ${{ github.event_name }} =~ pull_request ]]; then
            echo "env=development" >> $GITHUB_OUTPUT
          elif [[ ${{ github.ref_name }} =~ main ]]; then
            echo "env=production" >> $GITHUB_OUTPUT
          fi

  build-app:
    needs: ['target-setup']
    environment: ${{ needs.target-setup.outputs.env }}
    env:
      env: ${{ needs.target-setup.outputs.env }}
      filename: 'datalogger-${{matrix.build.type}}-${{needs.target-setup.outputs.env}}'
      output: 'build/bin'
    name: 'Build | ${{ matrix.build.os }} ${{ matrix.build.platform }}'
    strategy:
      fail-fast: false
      matrix:
        build:
          [
            {
              name: 'Datalogger',
              platform: 'windows/amd64',
              type: windows-amd64,
              os: 'windows-latest',
              file: 'datalogger.exe',
              outdir: 'windows'
            },
            {
              name: 'Datalogger',
              platform: 'darwin/universal',
              type: macos,
              os: 'macos-latest',
              file: 'datalogger-macos-${{needs.target-setup.outputs.env}}.tar',
              outdir: 'macos'
            }
          ]
    runs-on: ${{matrix.build.os}}
    steps:
      - uses: actions/checkout@v4

      - name: Set LDFlags
        shell: bash
        run: |
          echo "ldFlags=-s -w -h -H windowsgui -X 'main.version=${{ github.sha }}'" >> $GITHUB_ENV

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.4

      - name: 'Install Pnpm'
        uses: pnpm/action-setup@v4
        with:
          version: '8.14'

      - name: Setup Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Get Wails
        run: go install github.com/wailsapp/wails/v2/cmd/wails@v2.9.1

      - name: Build Wails app
        run: |
          wails build -platform ${{matrix.build.platform}}

      - name: Package application
        if: matrix.build.type == 'macos'
        run: |
          cd build/bin
          tar -czf datalogger-${{matrix.build.type}}.tar Datalogger.app

      - name: Upload build artifacts
        if: github.event_name != 'pull_request'
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.build.file }}
          path: ${{env.output}}
