name: 'Build application'
on:
  workflow_dispatch:
    inputs:
      manual:
        description: 'Default value for tiggered workflows'
        type: boolean
        required: false
        default: true
  pull_request:
    branches:
      - develop
  push:
    branches:
      - develop
      - main
jobs:
  target-setup:
    name: 'Set up ENV'
    runs-on: 'windows-latest'
    outputs:
      env: ${{ steps.setvars.outputs.env }}
    steps:
      - name: Set build environment
        id: setvars
        shell: bash
        run: |
          if [[ ${{ github.ref_name }} =~ develop || ${{ github.event_name }} =~ pull_request ]]; then
            echo "env=development" >> $GITHUB_OUTPUT
          elif [[ ${{ github.ref_name }} =~ main ]]; then
            echo "env=production" >> $GITHUB_OUTPUT
          fi

  build-app:
    needs: ['target-setup']
    environment: ${{ needs.target-setup.outputs.env }}
    env:
      env: ${{ needs.target-setup.outputs.env }}
    name: 'Build | ${{ matrix.build.os }} ${{ matrix.build.platform }}'
    strategy:
      fail-fast: false
      matrix:
        build:
          - name: 'Datalogger'
            platform: 'windows/amd64'
            type: amd64
            os: 'windows-latest'
            file: 'datalogger.exe'
            outdir: 'windows'
          - name: 'Datalogger'
            platform: 'darwin/amd64'
            type: amd64
            os: 'macos-latest'
            file: 'Datalogger.app'
            outdir: 'amd64'
          - name: 'Datalogger'
            platform: 'darwin/arm64'
            type: arm64
            os: 'macos-latest'
            file: 'Datalogger.app'
            outdir: 'arm'
    runs-on: ${{matrix.build.os}}
    steps:
      - uses: actions/checkout@v4

      - name: Set LDFlags
        shell: bash
        run: |
          echo "ldFlags=-s -w -h -H windowsgui -X 'main.version=${{ github.sha }}'" >> $GITHUB_ENV

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.4

      - name: 'Install Pnpm'
        uses: pnpm/action-setup@v4
        with:
          version: '8.14'

      - name: Setup Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Set LDFlags
        shell: bash
        run: |
          echo "ldFlags=-s -w -h " >> $GITHUB_ENV

      - name: Get Wails
        run: go install github.com/wailsapp/wails/v2/cmd/wails@v2.9.1

      - name: Build Wails app
        run: |
          wails build -tags desktop,${{ env.env }} -platform ${{matrix.build.platform}}

      # - name: Build wails
      #   uses: dAppServer/wails-build-action@v2.2
      #   id: build
      #   with:
      #     build-name: ${{ matrix.build.outdir }}
      #     build-platform: ${{ matrix.build.platform }}
      #     package: true
      #     sign: false
      #     wails-version: 'v2.9.1'
      #     node-version: 20
      #     go-version: '1.22'
      # - name: Build Wails app
      #   run: |
      #     wails build -tags desktop,${{ env.env }} -ldflags "${{ env. ldFlags }}"

      - name: Upload build artifacts
        if: github.event_name != 'pull_request'
        uses: actions/upload-artifact@v2
        with:
          name: datalogger-${{matrix.build.type}}
          path: build/bin/*
